services:
  backend:
    build: ./learn-devops-backend
    ports:
    - "8080:8080"
    networks:
    - app-network
  
  frontend:
    build: ./learn-devops-frontend
    ports:
    - "80:80"
    networks:
    - app-network

networks:
  app-network:
    driver: bridge

  